### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by FxNeell** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t10-proj10_grupo04#24]

**Comment by marlonstt** [comment]
Criar duas personas por integrante da equipe:

Marlon:

1 Mateus Machado tem 32 anos e é vendedor autônomo no ramo do comércio digital(e-comerce). Ele trabalha em seu escritório em casa e pensa em se tornar um grande varejista no seguimento de eletrônicos. Devido ao grande aumento em sua vendas, seu tempo ficou curto para cuidar do seu automóvel e necessita de uma solução prática e agil para seu problema pois não pode parar seu negócio por muito tempo nestwe momento e alta nas vendas.

2 André Simão tem 28 anos, trabalha 10 horas por dia em um escritório de advocacia. Aos fins de semana gosta de ficar em casa e curtir suas series favoritas. Ele não possui conhecimento de produtos certos para limpeza do seu carro e prefere levar seu veículo em um lava jato, contudo, adoraria receber este serviço no conforto do seu lar para poder aproveitar ao máximo seu fim de semana.

Lucas:

3 Marcela Rangel tem 25 anos, é chef de cozinha em um restaurante. Em seu trabalho ela sempre procura fornecedores de alimentos locais que usam de métodos sustentáveis na produção. Ela faz isso para incentivar a economia sustentável em sua região e não se restringe apenas ao seu trabalho. Marcela esta sempre procurando novos produtos e serviços que compartilham dessa ideia.

4 Carlos Diniz tem 65 anos, é aposentado, casado, tem dois filhos e quatro netos. Mora em uma capital e tem um sítio em uma cidade do interior. Ele e sua esposa adoram passar uns dias no sítio e fazem isso com muita frequência, em casa estão sempre recebendo a visita de seus filhos e netos. Carlos não gosta do trânsito da capital onde mora, por isso, evita ao máximo tirar o carro da garagem quando está em casa. Para ele seria ótimo receber o serviço de lavagem automotiva sem ter que se deslocar até um lava-jato.
