### ISSUE TITLE
Definir os Objetivos

### ISSUE THREAD

**Issue by FxNeell** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e2-proj-int-t10-proj10_grupo04#32]

**Comment by LucasRVC** [comment]
Objetivo geral

Desenvolva um aplicativo para que usuários de lava-jato possam agendar serviço de lavagem automotiva em domicílio.

Objetivos específicos

identificar regiões onde existe demanda para este tipo de serviço

identificar os horários e dias da semana em que há maior procura pelo serviço de lavagem automotiva

Pesquisar pelas preferências dos usuários ao procurar um serviço de lava-jato

Estipular um tempo médio para a realização de cada serviço oferecido

Permitir ao usuário dar Feedback em relação à qualidade do serviço

Estimular o uso de práticas seguras para a realização do serviço
